//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUi.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeTrack.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissza a bejelentkezéshez.
        /// </summary>
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vissza a főmenübe.
        /// </summary>
        public static string BackToHome
        {
            get
            {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vissza a listához.
        /// </summary>
        public static string BackToList
        {
            get
            {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kliens azonosító.
        /// </summary>
        public static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kliens lista.
        /// </summary>
        public static string ClientList
        {
            get
            {
                return ResourceManager.GetString("ClientList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kliensnév.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliensek.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail újra .
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó újra.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elérhetőség.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Létrehozás.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Felhasználó létrehozása.
        /// </summary>
        public static string CreateNewUser
        {
            get
            {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Árfolyam.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Határidő.
        /// </summary>
        public static string DeadLine {
            get {
                return ResourceManager.GetString("DeadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil szerkesztése.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pénzszükséglet.
        /// </summary>
        public static string EffortInCurrency {
            get {
                return ResourceManager.GetString("EffortInCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Időszükséglet.
        /// </summary>
        public static string EffortInHours {
            get {
                return ResourceManager.GetString("EffortInHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elfelejtett jelszó.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Főoldal.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Főoldal.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijelentkezés.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Név.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó visszaállítás.
        /// </summary>
        public static string PasswordRecover {
            get {
                return ResourceManager.GetString("PasswordRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogosultság.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonszám.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projektek.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Projekt lista.
        /// </summary>
        public static string ProjectList
        {
            get
            {
                return ResourceManager.GetString("ProjectList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Projekt hozzáadása.
        /// </summary>
        public static string AddProject
        {
            get
            {
                return ResourceManager.GetString("AddProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regisztráció.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliens regisztráció.
        /// </summary>
        public static string RegisterClient {
            get {
                return ResourceManager.GetString("RegisterClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó regisztráció.
        /// </summary>
        public static string RegisterUser {
            get {
                return ResourceManager.GetString("RegisterUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Felhasználó lista.
        /// </summary>
        public static string UserList
        {
            get
            {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Jelszó emlékeztető.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szerep.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küldés.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Státusz.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Új státusz.
        /// </summary>
        public static string NewStatus
        {
            get
            {
                return ResourceManager.GetString("NewStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Státusz lista.
        /// </summary>
        public static string StatusList
        {
            get
            {
                return ResourceManager.GetString("StatusList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Státusz azonsoító.
        /// </summary>
        public static string StatusId {
            get {
                return ResourceManager.GetString("StatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csapat.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csapat azonosító.
        /// </summary>
        public static string TeamId {
            get {
                return ResourceManager.GetString("TeamId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Csapat hozzáadása.
        /// </summary>
        public static string AddNewTeam
        {
            get
            {
                return ResourceManager.GetString("AddNewTeam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Csapatnév.
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Csapat lista.
        /// </summary>
        public static string TeamList
        {
            get
            {
                return ResourceManager.GetString("TeamList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Csapatok.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználók.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weboldal.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weboldal.
        /// </summary>
        public static string CurrencyList
        {
            get
            {
                return ResourceManager.GetString("CurrencyList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weboldal.
        /// </summary>
        public static string NewCurrency
        {
            get
            {
                return ResourceManager.GetString("NewCurrency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weboldal.
        /// </summary>
        public static string PermissionList
        {
            get
            {
                return ResourceManager.GetString("PermissionList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weboldal.
        /// </summary>
        public static string NewPermission
        {
            get
            {
                return ResourceManager.GetString("NewPermission", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weboldal.
        /// </summary>
        public static string RoleList
        {
            get
            {
                return ResourceManager.GetString("RoleList", resourceCulture);
            }
        }

        public static string NewRole
        {
            get
            {
                return ResourceManager.GetString("NewRole", resourceCulture);
            }
        }

        public static string LoginPlease
        {
            get
            {
                return ResourceManager.GetString("LoginPlease", resourceCulture);
            }
        }
    }
}
