//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceProjectLink
    {
        public long InvoiceId { get; set; }
        public long ProjectID { get; set; }
        public long Id { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Project Project { get; set; }
    }
}
