//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    
    public enum PermissionTypeEnum : int
    {
        SuperUser = 0,
        ManageInvoiceForClient = 1,
        ManageInvoiceForSelf = 2,
        ManageTeams = 3,
        ManageUsers = 4,
        ManageProjects = 5,
        ManageTodos = 6,
        AddTimeRecords = 7,
        ManagePayments = 8
    }
}
