//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.InvoiceProjectLink = new HashSet<InvoiceProjectLink>();
            this.Todo = new HashSet<Todo>();
        }
    
        public string Name { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<short> EffortInHours { get; set; }
        public Nullable<decimal> EffortInCurrency { get; set; }
        public long TeamId { get; set; }
        public long StatusId { get; set; }
        public long ClientId { get; set; }
        public long Id { get; set; }
        public long CurrencyId { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Client Client { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceProjectLink> InvoiceProjectLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Todo> Todo { get; set; }
    }
}
