//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeTrackerModelContainer : DbContext
    {
        public TimeTrackerModelContainer()
            : base("name=TimeTrackerModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<InvoiceProjectLink> InvoiceProjectLink { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<RolePermissionLink> RolePermissionLink { get; set; }
        public virtual DbSet<UserTeamLink> UserTeamLink { get; set; }
        public virtual DbSet<Todo> Todo { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<TimeRecord> TimeRecord { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Client> Client { get; set; }
    }
}
